apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-nodejs-app-kxvb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-nodejs-app-kxvb
    app.kubernetes.io/part-of: nodejs-users
  name: simple-nodejs-app-kxvb
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: simple-nodejs-app-kxvb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: simple-nodejs-app-kxvb
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-oqpb-tenant/nodejs-users/simple-nodejs-app-kxvb@sha256:7788edaa8930c1282eaa797d64573fb96550e34673b239e0fbbda0cff8624fac
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
